variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "ansible-sg" {}
variable "key_name" {}
variable "instance-name" {}
variable "private-key" {}
variable "haproxy1" {}
variable "haproxy2" {}
variable "main-master" {}
variable "member-master01" {}
variable "member-master02" {}
variable "worker01" {}
variable "worker02" {}
variable "worker03" {}
variable "bastion-host" {}