---
- hosts: haproxy1
  become: true
  vars_files:
    - /home/ubuntu/ha-ip.yml
  tasks:
    - name: Installation of keepalived
      shell: sudo apt install keepalived -y

    - name: Configure keepalived  
      shell: |
        sudo bash -c 'echo "
        vrrp_instance haproxy-vip1 {
          state MASTER
          priority 100
          interface eth0
          virtual_router_id 60
          advert_int 1
          authentication {
            auth_type PASS
            auth_pass 1234
          }
          unicast_src_ip "{{HAPROXY1}}"
          unicast_peer {
            "{{HAPROXY2}}"
          }
          virtual_ipaddress {
            10.0.1.19/24
          }
        }" > /etc/keepalived/keepalived.conf'

    - name: Restart keepalived
      shell: |
        sudo systemctl restart keepalived
        sudo systemctl enable keepalived
        
- hosts: haproxy2
  become: true
  vars_files:
    - /home/ubuntu/ha-ip.yml
  tasks:
    - name: Installation of keepalived
      shell: sudo apt install keepalived -y

    - name: Configure keepalived  
      shell: |
        sudo bash -c 'echo "
        vrrp_instance haproxy-vip2 {
          state BACKUP
          priority 99
          interface eth0
          virtual_router_id 60
          advert_int 1
          authentication {
            auth_type PASS
            auth_pass 1234
          }
          unicast_src_ip "{{HAPROXY2}}"
          unicast_peer {
            "{{HAPROXY1}}"
          }
          virtual_ipaddress {
            10.0.1.19/24
          }
        }" > /etc/keepalived/keepalived.conf'

    - name: Restart keepalived
      shell: |
        sudo systemctl restart keepalived
        sudo systemctl enable keepalived