variable "ami" {}
variable "instance_type" {}
variable "subnets" {}
variable "subnets2" {}
variable "haproxy-sg" {}
variable "key_name" {}
variable "tag-haproxy1" {}
variable "tag-haproxy2" {}
variable "master1" {}
variable "master2" {}
variable "master3" {}